name: "✨ Feature Request"
description: "Have an idea for Solumati? Propose it here."
title: "[FEATURE]: "
labels: ["enhancement", "proposal"]
body:
  - type: markdown
    attributes:
      value: |
        We are always open to new ideas! Tell us about your suggestion.
  - type: textarea
    id: solution
    attributes:
      label: "Describe the Feature"
      description: "A clear and concise description of the feature you want implemented."
      placeholder: "I would like Solumati to support..."
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: "Is your feature request related to a problem?"
      description: "A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]"
      placeholder: "It is currently difficult to..."
  - type: textarea
    id: alternatives
    attributes:
      label: "Describe alternatives you've considered"
      description: "A clear and concise description of any alternative solutions or features you've considered."
  - type: textarea
    id: additional
    attributes:
      label: "Additional Context"
      description: "Add any other context or screenshots about the feature request here."
