import json
import zipfile
import io
from sqlalchemy.orm import Session
from app.db import models, schemas
from datetime import datetime

class DateTimeEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, datetime):
            return obj.isoformat()
        return super().default(obj)

def collect_user_data(db: Session, user_id: int):
    """
    Collects all stored data for a specific user complying with GDPR/DSGVO Article 15.
    """
    user = db.query(models.User).filter(models.User.id == user_id).first()
    if not user:
        return None

    # 1. Profile Data
    profile_data = {
        "id": user.id,
        "username": user.username,
        "real_name": user.real_name,
        "email": user.email,
        "about_me": user.about_me,
        "role": user.role,
        "created_at": user.created_at,
        "is_active": user.is_active,
        "is_verified": user.is_verified,
        "intent": user.intent,
        "image_url": user.image_url,
        "settings": {}
    }

    # Parse JSON fields
    try:
        profile_data["answers"] = json.loads(user.answers) if user.answers else {}
    except:
        profile_data["answers"] = user.answers

    try:
        profile_data["settings"] = json.loads(user.app_settings) if user.app_settings else {}
    except:
        pass

    # 2. Linked Accounts
    linked_accounts = []
    for acc in user.linked_accounts:
        linked_accounts.append({
            "provider": acc.provider,
            "provider_user_id": acc.provider_user_id,
            "email": acc.email,
            "connected_at": acc.created_at
        })

    # 3. Messages (Sent & Received)
    # GDPR: User has right to see copies of messages they sent.
    # Received messages are also part of their "inbox" data space.
    messages_sent = db.query(models.Message).filter(models.Message.sender_id == user_id).all()
    messages_received = db.query(models.Message).filter(models.Message.receiver_id == user_id).all()

    msgs_export = []
    for m in messages_sent:
        msgs_export.append({
            "direction": "sent",
            "to_user_id": m.receiver_id,
            "content": m.content, # In a real app this might be encrypted?
            "timestamp": m.timestamp,
            "is_read": m.is_read
        })
    for m in messages_received:
         msgs_export.append({
            "direction": "received",
            "from_user_id": m.sender_id,
            "content": m.content,
            "timestamp": m.timestamp,
            "is_read": m.is_read
        })

    # 4. Reports (Active transparency)
    reports_filed = db.query(models.Report).filter(models.Report.reporter_id == user_id).all()
    reports_received = db.query(models.Report).filter(models.Report.reported_id == user_id).all()

    reports_export = []
    for r in reports_filed:
        reports_export.append({
            "type": "filed_by_me",
            "reported_user_id": r.reported_id,
            "reason": r.reason,
            "status": r.status,
            "created_at": r.created_at
        })
    # NOTE: GDPR allows withholding data if it adversely affects rights of others.
    # Exposing WHO reported you might be a safety risk.
    # Usually you only disclose that you WERE reported and for what reason, but maybe REDACT the reporter?
    # Solumati is a small project, but let's be safe: Redact reporter ID for reports received.
    for r in reports_received:
        reports_export.append({
            "type": "filed_against_me",
            "reason": r.reason,
            "status": r.status,
            "created_at": r.created_at
            # No reporter_id included
        })

    # 5. Notifications
    notifications = db.query(models.Notification).filter(models.Notification.user_id == user_id).all()
    notifs_export = []
    for n in notifications:
        notifs_export.append({
            "title": n.title,
            "message": n.message,
            "type": n.type,
            "created_at": n.created_at,
            "is_read": n.is_read
        })

    return {
        "profile": profile_data,
        "linked_accounts": linked_accounts,
        "messages": msgs_export,
        "reports": reports_export,
        "notifications": notifs_export,
        "meta": {
            "export_date": datetime.utcnow(),
            "description": "Personal data export generated by Solumati."
        }
    }

def create_export_archive(user_data: dict) -> io.BytesIO:
    """
    Creates a ZIP file containing the user data in JSON format.
    Returns: BytesIO object of the ZIP file.
    """
    mem_zip = io.BytesIO()

    with zipfile.ZipFile(mem_zip, mode="w", compression=zipfile.ZIP_DEFLATED) as zf:
        # Write main JSON
        json_str = json.dumps(user_data, indent=2, cls=DateTimeEncoder)
        zf.writestr("solumati_data_export.json", json_str)

        # Add a README
        readme = (
            "Solumati Data Export\n"
            "====================\n\n"
            "This archive contains your personal data stored on our servers.\n"
            "The file 'solumati_data_export.json' contains structured data readable by machine.\n\n"
            "If you have questions, please contact support."
        )
        zf.writestr("README.txt", readme)

    mem_zip.seek(0)
    return mem_zip
