/* eslint-disable no-undef */
export const API_URL = (import.meta.env && import.meta.env.VITE_API_URL) ? import.meta.env.VITE_API_URL : "http://localhost:7777";
/* eslint-enable no-undef */
/* eslint-disable no-undef */
export const APP_VERSION = (typeof __APP_VERSION__ !== 'undefined') ? __APP_VERSION__ : '0.0.0';
/* eslint-enable no-undef */
export const APP_RELEASE_TYPE = "dev"; // stable, beta, nightly, development
export const APP_NAME = "Solumati";

export const FALLBACK = {
    // App & General
    'app.title': APP_NAME,
    'btn.back': 'Back',
    'btn.cancel': 'Cancel',
    'btn.save': 'Save',
    'btn.logout': 'Logout',
    'btn.close': 'Close',

    // Landing
    'landing.tagline': 'Stop Swiping. Start Connecting.',
    'landing.btn_login': 'Log in',
    'landing.btn_register': 'Register',
    'landing.btn_guest': 'Browse as guest',
    'landing.opensource': 'Free & Open Source',
    'landing.admin': 'Admin',
    'landing.legal': 'Legal',

    // Login
    'login.title': 'Welcome back',
    'login.subtitle': 'Welcome back! Please login to continue.',
    'login.btn_github': 'Login with GitHub',
    'login.btn_google': 'Login with Google',
    'login.btn_microsoft': 'Login with Microsoft',
    'login.or_email': 'Or with email',
    'login.forgot_pw': 'Forgot Password?',
    'btn.login_passkey': 'Login with Passkey',
    'label.email_user': 'Email or Username',
    'label.password': 'Password',
    'btn.login': 'Log in',

    // 2FA
    '2fa.title': 'Two-Factor Authentication',
    '2fa.desc_totp': 'Please enter the 6-digit code from your authenticator app.',
    '2fa.desc_email': 'We sent a code to your email. Please enter it below.',
    '2fa.desc_passkey': 'Please use your Passkey / Fingerprint to verify.',
    '2fa.label_code': 'Security Code',
    '2fa.btn_verify': 'Verify',
    '2fa.btn_passkey': 'Use Passkey',
    '2fa.error': 'Invalid code. Please try again.',
    '2fa.setup_title': 'Setup 2FA',
    '2fa.method_none': 'Disabled',
    '2fa.method_totp': 'Authenticator App (TOTP)',
    '2fa.method_email': 'Email Verification',
    '2fa.method_passkey': 'Passkey (WebAuthn)',
    '2fa.setup_totp_desc': 'Scan the QR code with your app (e.g. Google Authenticator) and enter the code below.',

    // 2FA Recovery (New)
    '2fa.trouble_logging_in': 'Trouble logging in?',
    '2fa.recovery_title': 'Account Recovery',
    '2fa.lost_device': 'Lost 2FA Device?',
    '2fa.reset_via_email': 'Reset via Email',
    '2fa.admin_emergency': 'Admin Emergency',
    '2fa.server_reset': 'Server Reset',
    '2fa.reset_title': 'Reset 2FA',
    '2fa.reset_desc': 'Enter your password to receive a reset code via email.',
    '2fa.enter_code_title': 'Enter Code',
    '2fa.enter_code_desc': 'Enter the 6-digit code sent to your email.',
    '2fa.emergency_title': 'Emergency Reset',
    '2fa.emergency_desc': 'Admin: Enter password to flag account for reset on next reboot.',
    '2fa.btn_send_code': 'Send Code',
    '2fa.btn_reset': 'Reset 2FA',
    '2fa.btn_flag_reset': 'Flag for Reset',
    '2fa.status_sending': 'Sending...',
    '2fa.status_verifying': 'Verifying...',
    '2fa.status_processing': 'Processing...',
    'btn.back_login': 'Back to Login',

    // Register
    'register.title': 'Create profile',
    'label.realname': 'First name',
    'header.personality': 'Personality Check',
    'scale.no': 'No',
    'scale.yes': 'Yes',
    'btn.register_now': 'Register for free',
    'register.disabled_title': 'Registration disabled',
    'legal.privacy_full.rights_text': 'You have the right to information, correction, deletion and restriction of the processing of your data.',
    'register.disabled_msg': 'The administrator has currently disabled new registrations. Please try again later.',
    'register.btn_back_home': 'Back to home',
    'register.check_mail': 'Account created! Please check your emails to activate the account.',

    // Verification
    'verify.success': 'Email successfully verified!',
    'verify.error': 'Verification link invalid or expired.',

    // Dashboard
    'dashboard.guest_warning': 'Guest mode: Images are blurred & chat is disabled.',
    'dashboard.no_matches': 'No matches found...',
    'dashboard.title': 'Your Matches',
    'dashboard.subtitle': 'People who vibe with you',
    'dashboard.match_score': 'Match Score',
    'match.pairing_text': 'Fits your values & goals',
    'dashboard.admin_panel': 'Admin Panel',

    // Admin Common
    'admin.title': 'Admin Console',
    'admin.access_title': 'Admin Panel Access',
    'admin.btn.unlock': 'Unlock',
    'admin.tab.users': 'Users',
    'admin.tab.reports': 'Reports',
    'admin.tab.settings': 'Settings',
    'admin.tab.diagnostics': 'Diagnostics',
    'admin.btn.refresh': 'Refresh',
    'admin.btn.roles': 'Roles Info',
    'admin.roles.title': 'System Role Overview',
    'role.admin.desc': 'Full access to all system settings and user data.',
    'role.moderator.desc': 'Can moderate users and content, but cannot change system settings.',
    'role.user.desc': 'Standard user with access to matching and profile functions.',
    'role.guest.desc': 'Restricted read access (blurred images, no chat).',
    'role.test': 'Test',
    'role.test.desc': 'Technical test user. Full "User" capabilities but restricted from changing security data (Email/Password).',

    // Admin Users
    'admin.table.id': 'ID',
    'admin.table.user': 'User',
    'admin.table.status': 'Status',
    'admin.table.registered': 'Registered',
    'admin.table.last_login': 'Last Login',
    'admin.table.role': 'Role',
    'admin.table.actions': 'Actions',
    'admin.status.active': 'Active',
    'admin.status.inactive': 'Inactive',
    'admin.status.pending': 'Pending',
    'admin.status.guest': 'Guest',
    'admin.btn.deactivate': 'Block',
    'admin.btn.activate': 'Unblock',
    'admin.btn.delete': 'Delete',
    'admin.btn.promote': 'Make Mod',
    'admin.btn.demote': 'Demote',
    'admin.btn.make_guest': 'Make Guest',
    'admin.btn.make_test': 'Make Test',
    'admin.btn.edit': 'Edit User',
    'admin.btn.verify': 'Verify User',
    'admin.no_users': 'No users found.',
    'admin.ban_until': 'Banned until',
    'admin.tooltip.visible': 'Visible in Matches',
    'admin.tooltip.hidden': 'Hidden from Matches',

    // Admin Reports
    'admin.reports.reporter': 'Reporter',
    'admin.reports.reported': 'Reported User',
    'admin.reports.reason': 'Reason',
    'admin.reports.decision': 'Decision',
    'admin.btn.no_violation': 'No Violation',
    'admin.btn.punish': 'Ban User',
    'admin.no_reports': 'No open reports. Everything clean!',

    // Admin Settings
    'admin.settings.registration_title': 'Registration & Access',
    'admin.settings.allow_reg': 'Allow Registration',
    'admin.settings.reg_enabled': 'Allow Registration',
    'admin.settings.require_verify': 'Force Email Verification',
    'admin.settings.allow_guest': 'Allow Guest Mode',
    'admin.settings.email_2fa_enabled': 'Enable Email 2FA Method',
    'admin.settings.domains': 'Allowed Domains (empty = all)',
    'admin.settings.blocked_domains': 'Blacklisted Domains',
    'admin.settings.domains_hint': 'Comma separated list.',
    'admin.settings.server_domain': 'Server Domain (e.g. https://myapp.com)',
    'admin.settings.mail_title': 'SMTP Mail Server',
    'admin.settings.mail_active': 'Enable Mail Sending',
    'admin.settings.smtp_server': 'Host',
    'admin.settings.smtp_port': 'Port',
    'admin.settings.user': 'User',
    'admin.settings.pass': 'Password',
    'admin.settings.from': 'Sender Address',
    'admin.settings.sender_name': 'Sender Name',
    'admin.settings.test_mail_btn': 'Send Test Email',
    'admin.settings.saved': 'Settings saved!',
    'admin.settings.save_error': 'Error saving settings.',
    'admin.settings.unsaved_warning': 'Please save changes first!',
    'admin.settings.encryption': 'Encryption',
    'admin.settings.enc_none': 'None',
    'admin.settings.enc_tls': 'STARTTLS',
    'admin.settings.enc_ssl': 'SSL',
    'admin.settings.enc_recommended': 'Recommended',
    'admin.settings.legal_title': 'Legal Company Data',
    'admin.settings.imprint': 'Imprint (Generated)',
    'admin.settings.privacy': 'Privacy (Generated)',
    'admin.settings.company_name': 'Company Name',
    'admin.settings.address_street': 'Street & Number',
    'admin.settings.address_zip_city': 'ZIP & City',
    'admin.settings.contact_email': 'Contact Email',
    'admin.settings.contact_phone': 'Contact Phone',
    'admin.settings.ceo_name': 'CEO / Representative',
    'admin.settings.register_court': 'Register Court',
    'admin.settings.register_number': 'Register Number',
    'admin.settings.vat_id': 'VAT ID',

    // Admin Modal
    'admin.modal.punish_title': 'Block User',
    'admin.modal.edit_title': 'Edit User',
    'admin.modal.reason': 'Type',
    'admin.modal.custom_reason': 'Reason text (visible to user)',
    'admin.reason.reported': 'Reported (Violation)',
    'admin.reason.manual': 'Manual Deactivation',
    'admin.reason.tempban': 'Temporary Ban',
    'admin.reason.unknown': 'Other / Unknown',
    'admin.modal.duration': 'Duration (Hours)',
    'admin.modal.duration_hint': 'Account will be reactivated automatically after this time.',
    'admin.btn.execute_ban': 'Execute Ban',
    'admin.user.visible': 'Visible in Matches',
    'admin.user.visible_hint': 'Uncheck if this account is strictly for administration.',
    'admin.user.pw_reset': 'Password (Reset)',
    'admin.user.pw_new': 'New Password',

    // Admin Diagnostics
    'admin.diag.system_status': 'System Status',
    'admin.diag.version': 'Version',
    'admin.diag.internet': 'Internet Connection',
    'admin.diag.disk': 'Disk Space',
    'admin.diag.database': 'Database',
    'admin.diag.api': 'API Reachability',
    'admin.diag.changelog': 'Changelog',
    'admin.diag.update_available': 'Update Available!',
    'admin.diag.up_to_date': 'Up to date',
    'admin.diag.online': 'Online',
    'admin.diag.offline': 'Offline',
    'admin.diag.connected': 'Connected',
    'admin.diag.disconnected': 'Error',
    'admin.diag.free': 'Free',

    // Profile
    'profile.title': 'Your Profile',
    'profile.about_me': 'About Me - Tell something exciting!',
    'profile.btn_settings': 'Account Security & Settings',
    'profile.saved': 'Profile saved.',

    // Settings
    'settings.title': 'Account Settings',
    'settings.tab_app': 'App Settings',
    'settings.tab_account': 'Account & Security',
    'settings.push_title': 'Notifications',
    'settings.push_label': 'Push Notifications',
    'settings.push_desc': 'Receive updates about new matches and messages.',
    'settings.display_title': 'Display',
    'settings.change_mail': 'Change Email Address',
    'settings.change_pw': 'Change Password',
    'settings.curr_pw': 'Current Password (confirm)',
    'settings.new_pw': 'New Password',
    'settings.btn_reset_pw': 'Reset Password (Logout)',
    'settings.delete_acc': 'Permanently Delete Account',
    'settings.delete_confirm': 'Are you sure? All data will be lost.',
    'settings.success': 'Successfully updated.',
    'settings.reverify': 'Please verify your new email address.',
    'settings.2fa_title': 'Two-Factor Authentication (2FA)',
    'settings.2fa_current': 'Current Method:',
    'settings.btn_setup_totp': 'Setup TOTP (App)',
    'settings.btn_setup_email': 'Use Email 2FA',
    'settings.btn_setup_passkey': 'Register Passkey',
    'settings.btn_disable_2fa': 'Disable 2FA'
};